/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juegopreguntas.vista;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Random;
import juegopreguntas.conexion.Conexion;
import juegopreguntas.model.Categoria;
import juegopreguntas.model.Pregunta;
import juegopreguntas.model.Ronda;

/**
 *
 * @author Angelita
 */
public class JugarView extends javax.swing.JFrame {

    private int contRondas=0;
    /**
     * Creates new form JugarView
     */
    public JugarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_opciones = new javax.swing.ButtonGroup();
        jl_descripcionRonda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jl_premio = new javax.swing.JLabel();
        jl_desc_preg = new javax.swing.JLabel();
        jl_desc_categoria = new javax.swing.JLabel();
        jrb_opcion1 = new javax.swing.JRadioButton();
        jrb_opcion2 = new javax.swing.JRadioButton();
        jrb_opcion3 = new javax.swing.JRadioButton();
        jrb_opcion4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_descripcionRonda.setText("DESCRIPCIÓN RONDA");

        jLabel2.setText("PREMIO: ");

        jl_premio.setText("$VALOR PREMIO");

        jl_desc_preg.setText("Descripción Pregunta.....");

        jl_desc_categoria.setText("Descripción de la categoria...");

        bg_opciones.add(jrb_opcion1);
        jrb_opcion1.setText("Opción de respuesta 1....");

        bg_opciones.add(jrb_opcion2);
        jrb_opcion2.setText("Opción de respuesta 2.....");
        jrb_opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_opcion2ActionPerformed(evt);
            }
        });

        bg_opciones.add(jrb_opcion3);
        jrb_opcion3.setText("Opción de respuesta 3.....");

        bg_opciones.add(jrb_opcion4);
        jrb_opcion4.setText("Opción de respuesta 4....");
        jrb_opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_opcion4ActionPerformed(evt);
            }
        });

        jButton1.setText("VALIDAR RESPUESTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jl_descripcionRonda)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_premio)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(264, 264, 264))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_opcion2)
                            .addComponent(jrb_opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrb_opcion3)
                            .addComponent(jrb_opcion4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jl_desc_categoria))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jl_desc_preg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_descripcionRonda)
                    .addComponent(jLabel2)
                    .addComponent(jl_premio))
                .addGap(41, 41, 41)
                .addComponent(jl_desc_preg)
                .addGap(39, 39, 39)
                .addComponent(jl_desc_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jrb_opcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_opcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_opcion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_opcion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_opcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_opcion2ActionPerformed

    private void jrb_opcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_opcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_opcion4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JugarView().setVisible(true);
            }
        });
    }
    
    /*--------------------------------------------------------------
    función para llenar jlabels con los datos de cada objeto tipo ronda, las cuales se
    obtienen de la base de datos
    ----------------------------------------------------------------*/
    public void llenarJLRondas(int contRonda){
        
        Ronda ronda = new Ronda();
        ArrayList<Ronda> listRondas = new ArrayList<>();
        listRondas = consultarRondas();
        jl_descripcionRonda.setText(listRondas.get(contRonda).getDescripcion());
        jl_premio.setText("$ " + String.valueOf(listRondas.get(contRonda).getPremio()));
        seleccionarPreguntaAleatoria(consultarPreguntasByCategoria());
        
    }
    
    
    /*--------------------------------------------------------------
    función que retorna una lista de objetos de tipo Ronda, los cuales
    se obtienen de la base de datos, por medio de una consulta SQL.
    --------------------------------------------------------------*/
    public ArrayList<Ronda> consultarRondas(){
        
        ArrayList<Ronda> listRondas = new ArrayList<>();
        try{
            Conexion conecta = new Conexion();
            Connection con = (Connection) conecta.getConexion();
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM ronda;");
            
            int i=0;
            while(rs.next())  {
                Ronda ronda = new Ronda();
                ronda.setId(Integer.parseInt(rs.getString(1)));
                System.out.println("id_ronda:  " + ronda.getId());
                ronda.setDescripcion(rs.getString(2));
                System.out.println("descripción_ronda: " + ronda.getDescripcion());
                ronda.setPremio(Integer.parseInt(rs.getString(3)));
                System.out.println("premio:  " + ronda.getPremio());
                i=i+1;
                listRondas.add(ronda);
            }
            con.close();
                        
        } catch (Exception e){
            System.out.println(e);            
        }
        
        return listRondas;
    }
    
        /*--------------------------------------------------------------
    función que selecciona por medio de la generacion de un número aleatorio,
    un item de la lista de preguntas que se recibe como parametro
    --------------------------------------------------------------*/
    private void seleccionarPreguntaAleatoria(ArrayList<Pregunta> listaPreguntas) {
        
       
        Random r = new Random();
        int numeroAleatorio = r.nextInt(4)+1;  // Entre 0 y 5, más 1.
        System.out.println("numero aleatorio: " + numeroAleatorio);
        
        jl_desc_preg.setText(listaPreguntas.get(numeroAleatorio).getDescripcion());
        
    }
    
    
    
        /*--------------------------------------------------------------
    función que retorna una lista de objetos tipo Pregunta, estos datos
    se obtienen de la base de datos, por medio de una consulta SQL.
    --------------------------------------------------------------*/
    private ArrayList<Pregunta> consultarPreguntasByCategoria(){
        
            ArrayList<Pregunta> listPreguntas = new ArrayList<>();
        try{
            Conexion conecta = new Conexion();
            Connection con = (Connection) conecta.getConexion();
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT `pregunta`.`id_preg`, `pregunta`.`descripcion_preg` " +
                                        "FROM `pregunta` "
                                        + "WHERE pregunta.id_cate_preg = "+ contRondas+1 +";");
            
            int i=0;
            while(rs.next())  {
                Pregunta pregunta = new Pregunta();
                pregunta.setId(Integer.parseInt(rs.getString(1)));
                System.out.println("id_preg:  " + pregunta.getId());
                pregunta.setDescripcion(rs.getString(2));
                System.out.println("descripción_preg: " + pregunta.getDescripcion());
                i=i+1;
                listPreguntas.add(pregunta);
            }
                        
        } catch (Exception e){
            System.out.println(e);            
        }
        
        return listPreguntas;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_opciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jl_desc_categoria;
    private javax.swing.JLabel jl_desc_preg;
    private javax.swing.JLabel jl_descripcionRonda;
    private javax.swing.JLabel jl_premio;
    private javax.swing.JRadioButton jrb_opcion1;
    private javax.swing.JRadioButton jrb_opcion2;
    private javax.swing.JRadioButton jrb_opcion3;
    private javax.swing.JRadioButton jrb_opcion4;
    // End of variables declaration//GEN-END:variables
}
